// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class LkpProductDetailsAttribute
{
    public int ProductDetailAttributeId { get; set; }

    public int ProductDetailId { get; set; }

    public int AttributeId { get; set; }

    public int MeasureUnitId { get; set; }

    public virtual lkpAttribute Attribute { get; set; }

    public virtual LkpMeasureUnite MeasureUnit { get; set; }

    public virtual TblProductDetail ProductDetail { get; set; }
}