// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class LkpPromotion
{
    public int PromotionId { get; set; }

    public string PromotionName { get; set; }

    public decimal DiscountPercentage { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual ICollection<TblProductDetail> ProductDetails { get; set; } = new List<TblProductDetail>();
}