// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class TblProductDetail
{
    public int ProductDetailId { get; set; }

    public string SerialNumber { get; set; }

    public int ProductId { get; set; }

    public decimal Price { get; set; }

    public string Description { get; set; }

    public virtual ICollection<LkpProductDetailsAttribute> LkpProductDetailsAttributes { get; set; } = new List<LkpProductDetailsAttribute>();
    public virtual ICollection<LkpPromotion> Promotions { get; set; } = new List<LkpPromotion>();

    public virtual TblProduct Product { get; set; }

    public virtual ICollection<TblInventory> TblInventories { get; set; } = new List<TblInventory>();
}