// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class TblProduct
{
    public int ProductId { get; set; }

    public int TypeId { get; set; }

    public int AttributeId { get; set; }

    public int UserStoreId { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<LkpAttributesProduct> LkpAttributesProducts { get; set; } = new List<LkpAttributesProduct>();

    public virtual ICollection<TblOrderDetail> TblOrderDetails { get; set; } = new List<TblOrderDetail>();

    public virtual ICollection<TblProductImage> TblProductImages { get; set; } = new List<TblProductImage>();

    public virtual TblProductsDetail TblProductsDetail { get; set; }

    public virtual TblType Type { get; set; }

    public virtual TblUserStore UserStore { get; set; }
}