// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class TblReview
{
    public int ReviewId { get; set; }

    public int UserId { get; set; }

    public int OrderDetailsId { get; set; }

    public int Rating { get; set; }

    public string ReviewText { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual TblOrderDetail OrderDetails { get; set; }
}