// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Cartify.Domain.Entities;
using Cartify.Domain.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace Cartify.Infrastructure.Persistence;

public partial class AppDbContext : IdentityDbContext<TblUser>
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LkpAttribute> LkpAttributes { get; set; }

    public virtual DbSet<LkpAttributesProduct> LkpAttributesProducts { get; set; }

    public virtual DbSet<LkpMeasureUnite> LkpMeasureUnites { get; set; }

    public virtual DbSet<LkpOrderStatue> LkpOrderStatues { get; set; }

    public virtual DbSet<LkpPaymentType> LkpPaymentTypes { get; set; }

    public virtual DbSet<LkpProductDetailsAttribute> LkpProductDetailsAttributes { get; set; }

    public virtual DbSet<LkpShipementMethod> LkpShipementMethods { get; set; }

    public virtual DbSet<LkpUnitMeasuresAttribute> LkpUnitMeasuresAttributes { get; set; }

    public virtual DbSet<PasswordResetCode> PasswordResetCodes { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<TblAddress> TblAddresses { get; set; }

    public virtual DbSet<TblCategory> TblCategories { get; set; }

    public virtual DbSet<TblInventory> TblInventories { get; set; }

    public virtual DbSet<TblOrder> TblOrders { get; set; }

    public virtual DbSet<TblOrderDetail> TblOrderDetails { get; set; }

    public virtual DbSet<TblProduct> TblProducts { get; set; }

    public virtual DbSet<TblProductDetail> TblProductDetails { get; set; }

    public virtual DbSet<TblProductImage> TblProductImages { get; set; }

    public virtual DbSet<TblProductsDetail> TblProductsDetails { get; set; }

    public virtual DbSet<TblRefund> TblRefunds { get; set; }

    public virtual DbSet<TblReview> TblReviews { get; set; }

    public virtual DbSet<TblType> TblTypes { get; set; }

    public virtual DbSet<TblUserStore> TblUserStores { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var UserId = "8e75dee3-74df-43c8-8ded-ca9179be3480";
        var MerchantId = "fdcd17c2-f208-45cc-98d1-e80720cf7896";
        var AdminId = "c9ec0699-f839-4e8d-9bd3-12685ac984ab";
        var Roles = new List<IdentityRole>();
        Roles.Add(new IdentityRole { Id = UserId, Name = "User", NormalizedName = "USER", ConcurrencyStamp = UserId });
        Roles.Add(new IdentityRole { Id = MerchantId, Name = "Merchant", NormalizedName = "MERCHANT", ConcurrencyStamp = MerchantId });
        Roles.Add(new IdentityRole { Id = AdminId, Name = "Admin", NormalizedName = "ADMIN", ConcurrencyStamp = AdminId });
        modelBuilder.Entity<IdentityRole>().HasData(Roles);
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<TblUser>()
            .OwnsMany(u => u.RefreshTokens, rt =>
            {
                 rt.WithOwner().HasForeignKey("UserId"); // اسم العمود في الجدول
                 rt.Property(r => r.Token).IsRequired();
                 rt.HasKey("UserId", "Token"); // مفتاح مركب بسيط
             });
            modelBuilder.Entity<LkpAttribute>(entity =>
            {
              
                entity.HasKey(e => e.AttributeId);
                entity.ToTable("lkpAttributes");
                entity.Property(e => e.AttributeId).ValueGeneratedNever();
                entity.Property(e => e.CreatedDate)
                    .HasDefaultValueSql("(getdate())")
                    .HasColumnType("datetime");
                entity.Property(e => e.DeletedDate).HasColumnType("datetime");
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);
             });
   

        modelBuilder.Entity<LkpAttributesProduct>(entity =>
        {
            entity.HasKey(e => e.AttributeProductId);

            entity.HasIndex(e => e.AttriputeId, "IX_LkpAttributesProducts_AttriputeId");

            entity.HasIndex(e => e.ProductId, "IX_LkpAttributesProducts_ProductId");

            entity.Property(e => e.AttributeProductId).ValueGeneratedNever();

            entity.HasOne(d => d.Attripute).WithMany(p => p.LkpAttributesProducts)
                .HasForeignKey(d => d.AttriputeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LkpAttributesProducts_lkpAttributes");

            entity.HasOne(d => d.Product).WithMany(p => p.LkpAttributesProducts)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LkpAttributesProducts_TblProducts");
        });

        modelBuilder.Entity<LkpMeasureUnite>(entity =>
        {
            entity.HasKey(e => e.UnitOfMeasureId).HasName("PK_LkpUnitOfMeasures");

            entity.Property(e => e.UnitOfMeasureId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<LkpOrderStatue>(entity =>
        {
            entity.HasKey(e => e.OrderStatuesId);

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<LkpPaymentType>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK_TblPayment");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<LkpProductDetailsAttribute>(entity =>
        {
            entity.HasKey(e => e.ProductDetailAttributeId);

            entity.HasOne(d => d.Attribute).WithMany(p => p.LkpProductDetailsAttributes)
                .HasForeignKey(d => d.AttributeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LkpProductDetailsAttributes_lkpAttributes");

            entity.HasOne(d => d.MeasureUnit).WithMany(p => p.LkpProductDetailsAttributes)
                .HasForeignKey(d => d.MeasureUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LkpProductDetailsAttributes_LkpMeasureUnites");

            entity.HasOne(d => d.ProductDetail).WithMany(p => p.LkpProductDetailsAttributes)
                .HasForeignKey(d => d.ProductDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LkpProductDetailsAttributes_TblProductDetails");
        });

        modelBuilder.Entity<LkpShipementMethod>(entity =>
        {
            entity.HasKey(e => e.ShipementMethodId);

            entity.Property(e => e.ShipementMethodId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Fees).HasColumnType("decimal(9, 2)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<LkpUnitMeasuresAttribute>(entity =>
        {
            entity.HasKey(e => e.UnitMeasureAttributeId);

            entity.HasIndex(e => e.AttributeId, "IX_LkpUnitMeasuresAttributes_AttributeId");

            entity.HasIndex(e => e.UnitOfMeasureId, "IX_LkpUnitMeasuresAttributes_UnitOfMeasureId");

            entity.Property(e => e.UnitMeasureAttributeId).ValueGeneratedNever();

            entity.HasOne(d => d.Attribute).WithMany(p => p.LkpUnitMeasuresAttributes)
                .HasForeignKey(d => d.AttributeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LkpUnitOfMeasuresAttributes_lkpAttributes");

            entity.HasOne(d => d.UnitOfMeasure).WithMany(p => p.LkpUnitMeasuresAttributes)
                .HasForeignKey(d => d.UnitOfMeasureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LkpUnitOfMeasuresAttributes_LkpUnitOfMeasures");
        });

        modelBuilder.Entity<PasswordResetCode>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_PasswordResetCodes_UserId");

            entity.Property(e => e.Code).IsRequired();
            entity.Property(e => e.UserId).IsRequired();
        });



        modelBuilder.Entity<TblAddress>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("PK_TblAdresses_1");

            entity.HasIndex(e => e.UserId, "IX_TblAddresses_UserId");

            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.IsDefault).HasDefaultValue(false);
            entity.Property(e => e.PostalCode).HasMaxLength(50);
            entity.Property(e => e.State).HasMaxLength(50);
            entity.Property(e => e.StreetAddress).HasMaxLength(50);
        });

        modelBuilder.Entity<TblCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId);

            entity.Property(e => e.CategoryId).ValueGeneratedNever();
            entity.Property(e => e.CategoryDescription).IsRequired();
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TblInventory>(entity =>
        {
            entity.HasKey(e => e.InventoryId);

            entity.ToTable("TblInventory");

            entity.HasIndex(e => e.ProductDetailId, "IX_TblInventory_ProductDetailId");

            entity.Property(e => e.InventoryId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");

            entity.HasOne(d => d.ProductDetail).WithMany(p => p.TblInventories)
                .HasForeignKey(d => d.ProductDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblInventory_TblProductDetails1");

            entity.HasOne(d => d.ProductDetailNavigation).WithMany(p => p.TblInventories)
                .HasForeignKey(d => d.ProductDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblInventory_TblProductsDetails");
        });

        modelBuilder.Entity<TblOrder>(entity =>
        {
            entity.HasKey(e => e.OrderId);

            entity.HasIndex(e => e.OrderStatuesId, "IX_TblOrders_OrderStatuesId");

            entity.HasIndex(e => e.PaymentTypeId, "IX_TblOrders_PaymentTypeId");

            entity.HasIndex(e => e.ShipmentMethodId, "IX_TblOrders_ShipmentMethodId");

            entity.Property(e => e.OrderId).HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.GrantTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Tax).HasColumnType("decimal(9, 2)");
            entity.Property(e => e.TotalDiscount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.OrderStatues).WithMany(p => p.TblOrders)
                .HasForeignKey(d => d.OrderStatuesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblOrders_LkpOrderStatues");

            entity.HasOne(d => d.PaymentType).WithMany(p => p.TblOrders)
                .HasForeignKey(d => d.PaymentTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblOrders_LkpPaymentTypes");

            entity.HasOne(d => d.ShipmentMethod).WithMany(p => p.TblOrders)
                .HasForeignKey(d => d.ShipmentMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblOrders_LkpShipementMethods");
        });

        modelBuilder.Entity<TblOrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId);

            entity.HasIndex(e => e.OrderId, "IX_TblOrderDetails_OrderId");

            entity.HasIndex(e => e.ProductId, "IX_TblOrderDetails_ProductId");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Discount).HasColumnType("decimal(9, 2)");
            entity.Property(e => e.OrderId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Order).WithMany(p => p.TblOrderDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblOrderProducts_TblOrders");

            entity.HasOne(d => d.Product).WithMany(p => p.TblOrderDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblOrderProducts_TblProducts");
        });

        modelBuilder.Entity<TblProduct>(entity =>
        {
            entity.HasKey(e => e.ProductId);

            entity.HasIndex(e => e.TypeId, "IX_TblProducts_TypeId");

            entity.HasIndex(e => e.UserStoreId, "IX_TblProducts_UserStoreId");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Type).WithMany(p => p.TblProducts)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblProducts_TblTypes");

            entity.HasOne(d => d.UserStore).WithMany(p => p.TblProducts)
                .HasForeignKey(d => d.UserStoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblProducts_TblUserStore1");
        });

        modelBuilder.Entity<TblProductDetail>(entity =>
        {
            entity.HasKey(e => e.ProductDetailId);

            entity.Property(e => e.ProductDetailId).ValueGeneratedNever();
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.TblProductDetails)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblProductDetails_TblProducts");
        });

        modelBuilder.Entity<TblProductImage>(entity =>
        {
            entity.HasIndex(e => e.ProductId, "IX_TblProductImages_ProductId");

            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("ImageURL");

            entity.HasOne(d => d.Product).WithMany(p => p.TblProductImages)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblProductImages_TblProducts");
        });

        modelBuilder.Entity<TblProductsDetail>(entity =>
        {
            entity.HasKey(e => e.ProductDetailId);

            entity.HasIndex(e => e.UnitMeasureAttributeId, "IX_TblProductsDetails_UnitMeasureAttributeId");

            entity.Property(e => e.ProductDetailId).ValueGeneratedNever();
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProductId).HasColumnName("productId");

            entity.HasOne(d => d.ProductDetail).WithOne(p => p.TblProductsDetail)
                .HasForeignKey<TblProductsDetail>(d => d.ProductDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblProductsDetails_TblProducts");

            entity.HasOne(d => d.UnitMeasureAttribute).WithMany(p => p.TblProductsDetails)
                .HasForeignKey(d => d.UnitMeasureAttributeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblProductsDetails_LkpUnitMeasuresAttributes");
        });

        modelBuilder.Entity<TblRefund>(entity =>
        {
            entity.HasKey(e => e.RefundId);

            entity.HasIndex(e => e.OrderDetailId, "IX_TblRefunds_OrderDetailId");

            entity.Property(e => e.RefundId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RefundStatues)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.TblRefunds)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblRefunds_TblOrderDetails");
        });

        modelBuilder.Entity<TblReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId);

            entity.HasIndex(e => e.OrderDetailsId, "IX_TblReviews_OrderDetailsId");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.ReviewText).HasMaxLength(500);

            entity.HasOne(d => d.OrderDetails).WithMany(p => p.TblReviews)
                .HasForeignKey(d => d.OrderDetailsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblReviews_TblOrderDetails");
        });

        modelBuilder.Entity<TblType>(entity =>
        {
            entity.HasKey(e => e.TypeId);

            entity.HasIndex(e => e.CategoryId, "IX_TblTypes_CategoryId");

            entity.Property(e => e.TypeId).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.TypeDescription)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Category).WithMany(p => p.TblTypes)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblTypes_TblCategories");
        });

        modelBuilder.Entity<TblUserStore>(entity =>
        {
            entity.HasKey(e => e.UserStorId);

            entity.ToTable("TblUserStore");

            entity.HasIndex(e => e.InventoryId, "IX_TblUserStore_InventoryId");

            entity.HasIndex(e => e.UserId, "IX_TblUserStore_UserId");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedDate).HasColumnType("datetime");
            entity.Property(e => e.StoreName).HasMaxLength(50);

            entity.HasOne(d => d.Inventory).WithMany(p => p.TblUserStores)
                .HasForeignKey(d => d.InventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblUserStore_TblInventory");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}