// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class PasswordResetCode
{
    public int Id { get; set; }

    public string Code { get; set; }

    public DateTime Expiration { get; set; }

    public bool IsUsed { get; set; }

    public string UserId { get; set; }
}