// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class TblAddress
{
    public int AddressId { get; set; }

    public string UserId { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string StreetAddress { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public bool? IsDefault { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }
}