// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Domain.Models;

public partial class TblOrder
{
    public string OrderId { get; set; }

    public DateTime OrderDate { get; set; }

    public int OrderStatuesId { get; set; }

    public int PaymentTypeId { get; set; }

    public decimal TotalPrice { get; set; }

    public decimal? TotalDiscount { get; set; }

    public int CustomerId { get; set; }

    public int ShipmentMethodId { get; set; }

    public decimal GrantTotal { get; set; }

    public decimal Tax { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual LkpOrderStatue OrderStatues { get; set; }

    public virtual LkpPaymentType PaymentType { get; set; }

    public virtual LkpShipementMethod ShipmentMethod { get; set; }

    public virtual ICollection<TblOrderDetail> TblOrderDetails { get; set; } = new List<TblOrderDetail>();
}