// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class LkpUnitOfMeasuresAttribute
{
    public int UnitOfMeasurementAttributeId { get; set; }

    public int UnitOfMeasureId { get; set; }

    public int AttributeId { get; set; }

    public int? CreatedBy1 { get; set; }

    public bool IsDeleted1 { get; set; }

    public DateTime CreatedDate1 { get; set; }

    public int? UpdatedBy1 { get; set; }

    public int? DeletedBy1 { get; set; }

    public DateTime? DeletedDate1 { get; set; }

    public virtual LkpAttribute Attribute { get; set; }

    public virtual LkpUnitOfMeasure UnitOfMeasure { get; set; }
}