// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Backend.Models;

public partial class LkpUnitOfMeasure
{
    [Key]
    public int UnitOfMeasureId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedDate { get; set; }

    [InverseProperty("UnitOfMeasure")]
    public virtual ICollection<LkpUnitOfMeasuresAttribute> LkpUnitOfMeasuresAttributes { get; set; } = new List<LkpUnitOfMeasuresAttribute>();
}