// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class TblInventory
{
    public int InventoryId { get; set; }

    public int ProductDetailId { get; set; }

    public int QuantityAvailable { get; set; }

    public int QuantityReserved { get; set; }

    public int ReorderLevel { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual TblProductDetail ProductDetail { get; set; }

    public virtual TblProductsDetail ProductDetailNavigation { get; set; }

    public virtual ICollection<TblUserStore> TblUserStores { get; set; } = new List<TblUserStore>();
}