// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Backend.Models;

public partial class TblOrderDetail
{
    [Key]
    public int OrderDetailId { get; set; }

    public int ProductId { get; set; }

    [Required]
    [StringLength(50)]
    public string OrderId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal? Discount { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedDate { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("TblOrderDetails")]
    public virtual TblOrder Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("TblOrderDetails")]
    public virtual TblProduct Product { get; set; }

    [InverseProperty("OrderDetails")]
    public virtual ICollection<TblReview> TblReviews { get; set; } = new List<TblReview>();
}