// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Backend.Models;

public partial class TblOrder
{
    [Key]
    [StringLength(50)]
    public string OrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    public int OrderStatuesId { get; set; }

    public int PaymentTypeId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalPrice { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotalDiscount { get; set; }

    public int CustomerId { get; set; }

    public int ShipmentMethodId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal GrantTotal { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal Tax { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedDate { get; set; }

    [ForeignKey("OrderStatuesId")]
    [InverseProperty("TblOrders")]
    public virtual LkpOrderStatue OrderStatues { get; set; }

    [ForeignKey("PaymentTypeId")]
    [InverseProperty("TblOrders")]
    public virtual LkpPaymentType PaymentType { get; set; }

    [ForeignKey("ShipmentMethodId")]
    [InverseProperty("TblOrders")]
    public virtual LkpShipementMethod ShipmentMethod { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<TblOrderDetail> TblOrderDetails { get; set; } = new List<TblOrderDetail>();
}