// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Backend.Models;

public partial class TblProductImage
{
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    [Required]
    [Column("ImageURL")]
    [StringLength(255)]
    [Unicode(false)]
    public string ImageUrl { get; set; }

    public bool IsDeleted { get; set; }

    public int CreatedBy { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("TblProductImages")]
    public virtual TblProduct Product { get; set; }
}