// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Backend.Models;

public partial class TblProduct
{
    [Key]
    public int PtoductId { get; set; }

    public int TypeId { get; set; }

    public int AttributeId { get; set; }

    public int UserStoreId { get; set; }

    [Required]
    [StringLength(50)]
    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedDate { get; set; }

    [ForeignKey("AttributeId")]
    [InverseProperty("TblProducts")]
    public virtual LkpAttribute Attribute { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<TblInventory> TblInventories { get; set; } = new List<TblInventory>();

    [InverseProperty("Product")]
    public virtual ICollection<TblOrderDetail> TblOrderDetails { get; set; } = new List<TblOrderDetail>();

    [InverseProperty("Product")]
    public virtual ICollection<TblProductImage> TblProductImages { get; set; } = new List<TblProductImage>();

    [ForeignKey("TypeId")]
    [InverseProperty("TblProducts")]
    public virtual TblType Type { get; set; }

    [ForeignKey("UserStoreId")]
    [InverseProperty("TblProducts")]
    public virtual TblUserStore UserStore { get; set; }
}