// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class TblProductImage
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string ImageUrl { get; set; }

    public bool IsDeleted { get; set; }

    public int CreatedBy { get; set; }

    public virtual TblProduct Product { get; set; }
}