// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Core.Models;

public partial class LkpAttributesProduct
{
    public int AttributeProductId { get; set; }

    public int ProductId { get; set; }

    public int AttriputeId { get; set; }

    public bool IsDeleted { get; set; }

    public int? CreatedBy { get; set; }

    public virtual LkpAttribute Attripute { get; set; }

    public virtual TblProduct Product { get; set; }

    public virtual ICollection<TblProductDetail> TblProductDetails { get; set; } = new List<TblProductDetail>();
}