// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Core.Models;

public partial class LkpUnitMeasuresAttribute
{
    public int UnitMeasureAttributeId { get; set; }

    public int UnitOfMeasureId { get; set; }

    public int AttributeId { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public virtual LkpAttribute Attribute { get; set; }

    public virtual ICollection<TblProductDetail> TblProductDetails { get; set; } = new List<TblProductDetail>();

    public virtual ICollection<TblProductsDetail> TblProductsDetails { get; set; } = new List<TblProductsDetail>();

    public virtual LkpUnitOfMeasure UnitOfMeasure { get; set; }
}