// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Core.Models;

public partial class TblOrderDetail
{
    public int OrderDetailId { get; set; }

    public int ProductId { get; set; }

    public string OrderId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public decimal? Discount { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual TblOrder Order { get; set; }

    public virtual TblProduct Product { get; set; }

    public virtual ICollection<TblReview> TblReviews { get; set; } = new List<TblReview>();
}