// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Core.Models;

public partial class TblProductsDetail
{
    public int ProductDetailId { get; set; }

    public int UnitMeasureAttributeId { get; set; }

    public int ProductId { get; set; }

    public decimal Price { get; set; }

    public virtual TblProduct ProductDetail { get; set; }

    public virtual ICollection<TblInventory> TblInventories { get; set; } = new List<TblInventory>();

    public virtual LkpUnitMeasuresAttribute UnitMeasureAttribute { get; set; }
}