// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Core.Models;

public partial class TblRefund
{
    public int RefundId { get; set; }

    public int OrderDetailId { get; set; }

    public string RefundStatues { get; set; }

    public decimal RefundAmount { get; set; }

    public string Description { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual TblOrderDetail OrderDetail { get; set; }
}