// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cartify.Core.Models;

public partial class TblUser
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PasswordHash { get; set; }

    public int UserTypeId { get; set; }

    public string PermisionLevel { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public string BackupMobile { get; set; }

    public DateOnly? BirthDate { get; set; }

    public bool? Gender { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public int? DeletedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<TblAddress> TblAddresses { get; set; } = new List<TblAddress>();

    public virtual ICollection<TblUserStore> TblUserStores { get; set; } = new List<TblUserStore>();

    public virtual UserType UserType { get; set; }
}